package com.bionic.edu.sfc.entity.builder;

import com.bionic.edu.sfc.entity.User;
import com.bionic.edu.sfc.entity.UserRole;

import java.util.Date;

/**
 * Ivan
 * 2014.10
 */
public class UserBuilder {
    private String name = "Name generated by Builder";
    private UserRole userRole = UserRole.ROLE_CUSTOMER;
    private String login;
    private String passwordHash;
    private String description;
    private boolean active;
    private Date creationDate = new Date();

    private UserBuilder(String login) {
        this.login = login;
    }

    public static UserBuilder anUser(String login) {
        return new UserBuilder(login);
    }

    public UserBuilder withName(String name) {
        this.name = name;
        return this;
    }

    public UserBuilder withUserRole(UserRole userRole) {
        this.userRole = userRole;
        return this;
    }

    public UserBuilder withLogin(String login) {
        this.login = login;
        return this;
    }

    public UserBuilder withPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
        return this;
    }

    public UserBuilder withDescription(String description) {
        this.description = description;
        return this;
    }

    public UserBuilder withCreationDate(Date creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    public UserBuilder withActive(boolean active) {
        this.active = active;
        return this;
    }

    public User build() {
        User user = new User();
        user.setName(name);
        user.setUserRole(userRole);
        user.setLogin(login);
        user.setPasswordHash(passwordHash);
        user.setDescription(description);
        user.setCreationDate(creationDate);
        user.setActive(active);
        return user;
    }
}
